{% from 'macros/networking.jinja' import get_hostname with context -%}
services:
{%- if cookiecutter.__use_squid_block | bool %}
  squid:
    extends:
      file: compose/common.yml
      service: squid
    hostname: "{{ get_hostname('squid', 'prod') }}"
    volumes:
      - ./compose/config/squid.block.conf:/etc/squid/squid.conf:ro
      - ./compose/config/squid_blocked_domains.txt:/etc/squid/blocked_domains.txt:ro
      - ./compose/config/squid_blocked_ips.txt:/etc/squid/blocked_ips.txt:ro
      - ./compose/config/squid_blocked_ports.txt:/etc/squid/blocked_ports.txt:ro

{%- endif %}
  odoo:
    extends:
      file: compose/common.yml
      service: odoo
    build:
      target: isodoo-runtime-private
    hostname: "{{ get_hostname('odoo', 'prod') }}"
    networks:
      - dbnet
    env_file: 
      - compose/env/odoo.env
    environment:
      OCONF__options__db_host: "{{ get_hostname('db', 'prod') }}"
      OCONF__options__log_level: warn
      OCONF__options__log_handler: ":WARNING"
{%- if cookiecutter.__use_squid_block | bool %}
      http_proxy: "http://{{ get_hostname('squid', 'prod') }}:3129"
      https_proxy: "http://{{ get_hostname('squid', 'prod') }}:3129"
      HTTP_PROXY: "http://{{ get_hostname('squid', 'prod') }}:3129"
      HTTPS_PROXY: "http://{{ get_hostname('squid', 'prod') }}:3129"
{%- endif %}

  db:
    extends:
      file: compose/common.yml
      service: db
    hostname: "{{ get_hostname('db', 'prod') }}"
    networks:
      - dbnet
    secrets:
      - backup_password
    volumes:
{%- if cookiecutter.postgres_hba | length > 0 %}
      - ./compose/config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:ro,Z
{%- endif %}
{%- if cookiecutter.backup_use_pgbackrest %}
      - ./compose/config/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro,Z
{%- endif %}
{%- if cookiecutter.backup_use_resticprofile %}
      - ./compose/config/resticprofile.json:/etc/resticprofile/profiles.json:ro,Z
{%- endif %}
      - ./compose/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro,Z
      - filestore:/var/lib/odoo/data
    labels:
      ofelia.enabled: "true"
      ofelia.job-weekly.datecron.schedule: "@every 5s"
      ofelia.job-weekly.datecron.command: "pgbackrest --stanza=odoo --type=full backup >> /var/log/pgbackrest.log 2>&1"
      ofelia.job-dayly.datecron.schedule: "@every 5s"
      ofelia.job-dayly.datecron.command: "0 3 * * 1-6 pgbackrest --stanza=odoo backup >> /var/log/pgbackrest.log 2>&1"


networks:
  dbnet:
    driver: bridge

volumes:
  filestore:
  db:

secrets:
  backup_password:
    x-podman.relabel: Z
    file: compose/.secrets/backup_password.txt
  superuser_database_password:
    x-podman.relabel: Z
    file: compose/.secrets/superuser_database_password.txt
  odoo_database_password:
    x-podman.relabel: Z
    file: compose/.secrets/odoo_database_password.txt
