{% from 'macros/networking.jinja' import get_hostname with context -%}
{% from 'macros/config.jinja' import get_main_email_account with context -%}
services:
{%- if cookiecutter.__use_squid_allow | bool %}
  squid:
    image: ubuntu/squid:latest
    hostname: "{{ get_hostname('squid', 'ci') }}"
    volumes:
      - ./compose/config/squid.conf:/etc/squid/squid.conf:ro,Z
      - ./compose/config/squid_allowed_domains.txt:/etc/squid/allowed_domains.txt:ro,Z
      - ./compose/config/squid_allowed_ips.txt:/etc/squid/allowed_ips.txt:ro,Z
      - ./compose/config/squid_allowed_ports.txt:/etc/squid/allowed_ports.txt:ro,Z
      
{%- endif %}
  db:
    image: ghcr.io/grupoisonor/moouro:{{ cookiecutter.postgres_version }}
    env_file: compose/env/postgres.env
    secrets:
      - superuser_database_password
      - odoo_database_password
    hostname: "{{ get_hostname('db', 'ci') }}"
    networks:
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_ODOO_USER -d $$POSTGRES_ODOO_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  odoo:
    build:
      context: ./compose
      additional_contexts:
        deps: ./deps
        addons: ./addons
      target: isodoo-runtime-private
    secrets:
      - odoo_database_password
    depends_on:
      db:
        condition: service_healthy
{%- if cookiecutter.__use_squid_allow | bool %}
      squid:
        condition: service_started
{%- endif %}
    hostname: "{{ get_hostname('odoo', 'ci') }}"
    ports:
      - '127.0.0.1:{{ cookiecutter.odoo_version | int }}069:8069'
    networks:
      - dbnet
      - default
    env_file: 
      - compose/env/odoo.env
    environment:
{%- if cookiecutter.__use_squid_allow | bool %}
      http_proxy: "http://{{ get_hostname('squid', 'ci') }}:3129"
      https_proxy: "http://{{ get_hostname('squid', 'ci') }}:3129"
      no_proxy: "localhost,127.0.0.1,::1,*.local,10.0.0.0/8,192.168.0.0/16"
      HTTP_PROXY: "http://{{ get_hostname('squid', 'ci') }}:3129"
      HTTPS_PROXY: "http://{{ get_hostname('squid', 'ci') }}:3129"
      NO_PROXY: "localhost,127.0.0.1,::1,*.local,10.0.0.0/8,192.168.0.0/16"
{%- endif %}
      OCONF__options__log_level: info
      OCONF__options__log_handler: ":INFO"
      OCONF__options__db_host: "{{ get_hostname('db', 'ci') }}"
      OCONF__options__workers: 0
      OCONF__options__max_cron_threads: 0
      OCONF__options__test_enable: true
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8069/web/login || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s

networks:
  default:
  dbnet:
    driver: bridge

secrets:
  superuser_database_password:
    x-podman.relabel: Z
    file: .secrets/superuser_database_password.txt
  odoo_database_password:
    x-podman.relabel: Z
    file: .secrets/odoo_database_password.txt
