{% from 'macros/networking.jinja' import get_hostname with context -%}
{% from 'macros/config.jinja' import get_main_email_account with context -%}
services:
{%- if cookiecutter.__use_squid_allow | bool %}
  squid:
    image: ubuntu/squid:latest
    hostname: "{{ get_hostname('squid', 'ci') }}"
    volumes:
      - ./compose/config/squid.conf:/etc/squid/squid.conf:ro,Z
      - ./compose/config/squid_allowed_domains.txt:/etc/squid/allowed_domains.txt:ro,Z
      - ./compose/config/squid_allowed_ips.txt:/etc/squid/allowed_ips.txt:ro,Z
      - ./compose/config/squid_allowed_ports.txt:/etc/squid/allowed_ports.txt:ro,Z
{% endif %}
  db:
    image: ghcr.io/grupoisonor/moouro:{{ cookiecutter.postgres_version }}
    env_file: compose/env/postgres.env
    hostname: "{{ get_hostname('db', 'ci') }}"
    networks:
      - dbnet
    volumes:
      - db:{{ cookiecutter.__postgres_pgdata }}
    healthcheck:
{%- if cookiecutter.odoo_version|float < 19 %}
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_ODOO_USER -d $$POSTGRES_ODOO_DB"]
{%- else %}
      test: ["CMD-SHELL", "pg_isready"]
{%- endif %}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  odoo:
    build:
      context: ./compose
      additional_contexts:
        deps: ./deps
        addons: ./addons
      target: isodoo-runtime-private
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    depends_on:
      db:
        condition: service_healthy
{%- if cookiecutter.__use_squid_allow | bool %}
      squid:
        condition: service_started
{%- endif %}
    hostname: "{{ get_hostname('odoo', 'ci') }}"
    ports:
      - '{{ cookiecutter._bind_ip }}:{{ cookiecutter.odoo_version | int }}069:8069'
    networks:
      - dbnet
      - default
    env_file:
      - compose/env/odoo.env
    environment:
{%- if cookiecutter.__use_squid_allow | bool %}
      http_proxy: &http_proxy "http://{{ get_hostname('squid', 'ci') }}:3129"
      https_proxy: *http_proxy
      no_proxy: &no_proxy "{{ cookiecutter._squid_no_proxy }}"
      HTTP_PROXY: *http_proxy
      HTTPS_PROXY: *http_proxy
      NO_PROXY: *no_proxy
{%- endif %}
      OCONF__options__log_level: warn
      OCONF__options__log_handler: ":WARN"
      OCONF__options__db_host: "{{ get_hostname('db', 'ci') }}"
      OCONF__options__workers: 0
      OCONF__options__max_cron_threads: 0
{%- if cookiecutter.odoo_version|float < 19 %}
      OCONF__options__without_demo: all
{%- else %}
      OCONF__options__without_demo: True
{%- endif %}
      OCONF__test__enable: "True"
    volumes:
      - filestore:/var/lib/odoo/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8069/web/login || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s

networks:
  default:
  dbnet:
    driver: bridge

volumes:
  filestore:
  db:
